### ISSUE TITLE
Make it work with librsync 1.0.0+

### ISSUE THREAD

**Issue by diorahman** [diorahman/node-rdiff#4]

**Comment by diorahman** [comment]
Fixed https://github.com/diorahman/node-rdiff/commit/4e04a5b76d76321f5507422560874e4d40a01d6b

**Comment by diorahman** [comment]
cc. @FallingSnow

**Comment by FallingSnow** [comment]
Haha, PERFECT. Haven't tested it yet but it builds. I'll do some testing and come back and let you know if it's working as expected. Thanks again.
